### ISSUE TITLE
Ground and Ceiling Item Frames cause a crash when placed.

### ISSUE THREAD

**Issue by ItzChara12** [CaliMari/Minecraft-1.13-ACCESS-WITH-MORE-THINGS-THAN-THE-SNAPSHOTS#3]
Help please.

**Comment by CaliMari** [comment]
This is clearly an error because minecraft is not done yet... Try to tick Force Update in the Advanced section of the launcher and restart your PC.

**Comment by ItzChara12** [comment]
Thank you! It worked!

**Comment by CaliMari** [comment]
I'm glad i could help :)
